apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane-system
  namespace: crossplane-system
spec:
  interval: 5m
  chart:
    spec:
      chart: crossplane
      version: "1.19.0"
      sourceRef:
        kind: HelmRepository
        name: crossplane-system
        namespace: flux-system
  releaseName: crossplane
  install:
    createNamespace: true # Creates the crossplane-system namespace if it doesn’t exist
  values:
    # Optional customizations
    args:
      - "--debug" # Enable debug logging
      - "--enable-realtime-compositions"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
