# flux-values.yaml
sourceController:
  spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - --metrics-bind-address=:8080
  metrics:
    enabled: true
    service:
      enabled: true
      port: 8080
kustomizeController:
  metrics:
    enabled: true
    service:
      enabled: true
      port: 8080
helmController:
  metrics:
    enabled: true
    service:
      enabled: true
      port: 8080
notificationController:
  metrics:
    enabled: true
    service:
      enabled: true
      port: 8080