apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "69.7.3" # Use a specific version or range (check latest on ArtifactHub)
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  releaseName: kube-prometheus-stack
  install:
    createNamespace: true # Ensures the monitoring namespace is created if it doesn’t exist
  values:
    # Optional customizations
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
    grafana:
      # Use an existing secret for the admin user.
      admin:
        ## Name of the secret. Can be templated.
        existingSecret: "grafana-admin"
        userKey: username
        passwordKey: password
